apiVersion: apps/v1
kind: Deployment
metadata:
  name: deva
  labels:
    app.kubernetes.io/part-of: hello-worlda
    carto.run/workload-name: deva
    app.kubernetes.io/component: run
spec:
  replicas: 1
  selector:
    matchLabels:
      carto.run/workload-name: deva
  template:
    metadata:
      labels:
        carto.run/workload-name: deva
    spec:
      containers:
      - name: workload
        image: harbor.nordnet.fr/nordnet/cartodeva@sha256:ad85e9593191c501f02430a22707f44635f25e8f28d29b8b6aeba8cc7b58bea0
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 1Gi
          limits:
            cpu: "4"
            memory: 1Gi
        livenessProbe:
          httpGet:
            port: 8080
            path: /
          initialDelaySeconds: 60
          periodSeconds: 2
        readinessProbe:
          httpGet:
            port: 8080
            path: /
          initialDelaySeconds: 10
        securityContext:
          runAsUser: 1000
      imagePullSecrets:
      - name: registry-credentials

