apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: dev
  labels:
    app.kubernetes.io/part-of: hello-world
    carto.run/workload-name: dev
    app.kubernetes.io/component: run
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
      - name: workload
        image: harbor.nordnet.fr/nordnet/cartodev@sha256:4496d2d74a505d205230ef8013a3a47cf2422934f1af025f828bad7ac1cfd75f
        securityContext:
          runAsUser: 1000
      imagePullSecrets:
      - name: registry-credentials

