apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: dev
  labels:
    app.kubernetes.io/part-of: hello-world
    carto.run/workload-name: dev
    app.kubernetes.io/component: run
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
      - name: workload
        image: harbor.nordnet.fr/nordnet/cartodev@sha256:830f0dd76ce66721b0fec89f5890677f914dca579fca82ff6373aa5adce390ba
        securityContext:
          runAsUser: 1000
      imagePullSecrets:
      - name: registry-credentials

