apiVersion: apps/v1
kind: Deployment
metadata:
  name: deva
  labels:
    app.kubernetes.io/part-of: hello-worlda
    carto.run/workload-name: deva
    app.kubernetes.io/component: run
spec:
  replicas: 1
  selector:
    matchLabels:
      carto.run/workload-name: deva
  template:
    metadata:
      labels:
        carto.run/workload-name: deva
    spec:
      containers:
      - name: workload
        image: harbor.nordnet.fr/nordnet/cartodeva@sha256:76a5095f103184509f18ff2faa70762a71f4dcb8bae665c8f459df52f9d5af01
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 1Gi
          requests:
            cpu: 1Gi
            memory: 1Gi
        securityContext:
          runAsUser: 1000
      imagePullSecrets:
      - name: registry-credentials

